swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /add/person:
        post:
            tags:
                - user
            summary: addPerson user
            operationId: user#addPerson
            parameters:
                - name: AddPersonRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/Person'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AddPersonResponse'
                        required:
                            - success
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/PersonAlreadyExists'
                        required:
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalError'
                        required:
                            - message
            schemes:
                - http
    /delete/person/{id}:
        delete:
            tags:
                - user
            summary: deletePerson user
            operationId: user#deletePerson
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
                  format: int32
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalError'
                        required:
                            - message
            schemes:
                - http
    /get/person/{id}:
        get:
            tags:
                - user
            summary: getPerson user
            operationId: user#getPerson
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
                  format: int64
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Person'
            schemes:
                - http
    /hello/{name}:
        get:
            tags:
                - hello
            summary: sayHello hello
            operationId: hello#sayHello
            parameters:
                - name: name
                  in: path
                  description: Name to greet
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
    /user/{id}:
        get:
            tags:
                - user
            summary: getUser user
            operationId: user#getUser
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
definitions:
    AddPersonResponse:
        title: AddPersonResponse
        type: object
        properties:
            success:
                type: boolean
                example: true
        example:
            success: true
        required:
            - success
    InternalError:
        title: InternalError
        type: object
        properties:
            message:
                type: string
                example: Voluptatem expedita ut voluptas molestiae ut voluptate.
        example:
            message: Iste et nemo nemo libero iste.
        required:
            - message
    Person:
        title: Person
        type: object
        properties:
            age:
                type: integer
                example: 7360693971388168810
                format: int64
            email:
                type: string
                example: maye@lowe.com
                format: email
            id:
                type: integer
                example: 4755712726350755731
                format: int64
            mobileNo:
                type: string
                example: Fugit dolore.
            name:
                type: string
                example: Assumenda voluptatem.
        example:
            age: 4921722841199804186
            email: osbaldo.bahringer@kutch.name
            id: 6325081144157357547
            mobileNo: Voluptates assumenda ut ratione.
            name: Nostrum harum unde eaque esse qui.
    PersonAlreadyExists:
        title: PersonAlreadyExists
        type: object
        properties:
            message:
                type: string
                example: Ut illum facilis.
        example:
            message: Rerum sit voluptates ut accusamus ea.
        required:
            - message
