swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /add/borrower:
        post:
            tags:
                - Nihal
            summary: AddBorrower Nihal
            operationId: Nihal#AddBorrower
            parameters:
                - name: AddBorrowerRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/Borrower'
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/NihalAddBorrowerResponseBody'
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/BorrowerExists'
                        required:
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - message
            schemes:
                - http
    /add/person:
        post:
            tags:
                - user
            summary: addPerson user
            operationId: user#addPerson
            parameters:
                - name: AddPersonRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/Person'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AddPersonResponse'
                        required:
                            - success
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/PersonAlreadyExists'
                        required:
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalError'
                        required:
                            - message
            schemes:
                - http
    /delete/person/{id}:
        delete:
            tags:
                - user
            summary: deletePerson user
            operationId: user#deletePerson
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
                  format: int32
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalError'
                        required:
                            - message
            schemes:
                - http
    /get/person/{id}:
        get:
            tags:
                - user
            summary: getPerson user
            operationId: user#getPerson
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
                  format: int64
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Person'
            schemes:
                - http
    /hello/{name}:
        get:
            tags:
                - hello
            summary: sayHello hello
            operationId: hello#sayHello
            parameters:
                - name: name
                  in: path
                  description: Name to greet
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
    /user/{id}:
        get:
            tags:
                - user
            summary: getUser user
            operationId: user#getUser
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
definitions:
    AddPersonResponse:
        title: AddPersonResponse
        type: object
        properties:
            success:
                type: boolean
                example: true
        example:
            success: false
        required:
            - success
    Borrower:
        title: Borrower
        type: object
        properties:
            Address:
                type: string
                example: Qui repudiandae officia nostrum qui quia facilis.
            Age:
                type: integer
                example: 777919452
                format: int32
            Email:
                type: string
                example: uriah@dickinsonokuneva.org
                format: email
            FirstName:
                type: string
                example: Vitae voluptas iste libero.
            LastName:
                type: string
                example: Aspernatur qui enim at sed.
        description: Borrower struct coming as a payload
        example:
            Address: Incidunt ullam pariatur perspiciatis ea cupiditate aut.
            Age: 1228033880
            Email: berenice_orn@kossdach.biz
            FirstName: Odio et veniam eaque.
            LastName: Asperiores sunt eius odio cupiditate minima at.
    BorrowerExists:
        title: BorrowerExists
        type: object
        properties:
            message:
                type: string
                example: Harum aut.
            statusCode:
                type: integer
                example: 2129141258
                format: int32
        description: Borrower Already Exists
        example:
            message: Enim blanditiis.
            statusCode: 1767034417
        required:
            - message
    InternalError:
        title: InternalError
        type: object
        properties:
            message:
                type: string
                example: Adipisci doloribus.
        example:
            message: Nam quis tempore sapiente vel deleniti exercitationem.
        required:
            - message
    InternalServerError:
        title: InternalServerError
        type: object
        properties:
            message:
                type: string
                example: Quod eveniet dolores consequatur.
            statusCode:
                type: integer
                example: 791816658
                format: int32
        description: Internal Server Error
        example:
            message: Dolorem aut ut dignissimos sapiente veniam voluptatum.
            statusCode: 670089878
        required:
            - message
    NihalAddBorrowerResponseBody:
        title: NihalAddBorrowerResponseBody
        type: object
        properties:
            message:
                type: string
                example: Minus fugiat.
            statusCode:
                type: integer
                example: 1083134214
                format: int32
        example:
            message: Ad est dolores.
            statusCode: 1874580145
    Person:
        title: Person
        type: object
        properties:
            age:
                type: integer
                example: 3850064375773916627
                format: int64
            email:
                type: string
                example: helene@herzog.biz
                format: email
            id:
                type: integer
                example: 7735327543024720502
                format: int64
            mobileNo:
                type: string
                example: Enim cum.
            name:
                type: string
                example: Pariatur est.
        example:
            age: 8083778442467206613
            email: gerardo_murphy@beier.net
            id: 6809067453820455757
            mobileNo: Porro omnis aspernatur beatae.
            name: Voluptatem qui illo occaecati voluptatem labore in.
    PersonAlreadyExists:
        title: PersonAlreadyExists
        type: object
        properties:
            message:
                type: string
                example: Id dolorem.
        example:
            message: Dolore hic quas quae.
        required:
            - message
